name = "ssr-cache"
main = "src/index.ts"
compatibility_date = "2023-01-14"

workers_dev = true

[placement]
mode = "smart"

durable_objects.bindings = [{ class_name = "Counter", name = "COUNTER" }]


[env.ohg-d1]
name = "d1-www-ssr-cache-v2"
routes = ["d1-www.ohgar.com/es/test", "d1-www.ohgar.com/es/test*"]

[env.ohg-d1.vars]
ORIGIN_HOST = "d1-www.ohgar.com"
ORIGIN_PROTOCOL = "https"
ORIGIN_PORT = "443"
FORCED_EDGE_CACHE_CONTROL = "public, max-age=14400"
TRACKING_PARAMS = "gclid,gclsrc,fbclid,utm_source,utm_medium,utm_campaign,utm_content"
SSR_RETRIES = "4000,6000,10000"

[env.ohg-s1]
name = "s1-www-ssr-cache-v2"
routes = ["s1-www.ohgar.com/es/test", "s1-www.ohgar.com/es/test/*"]

[env.ohg-s1.vars]
ORIGIN_HOST = "s1-www.ohgar.com"
ORIGIN_PROTOCOL = "https"
ORIGIN_PORT = "443"
FORCED_EDGE_CACHE_CONTROL = "public, max-age=28800"
TRACKING_PARAMS = "gclid,gclsrc,fbclid,utm_source,utm_medium,utm_campaign,utm_content"
SSR_RETRIES = "4000,6000,10000"

[env.ohg-p1]
name = "p1-www-ssr-cache-v2"
routes = ["www.ohgar.com/es/c/test-ssr-cache*"]
analytics_engine_datasets = [
    { binding = "SSR_CACHE", dataset = "ssr_cache_p1" }
]
#r2_buckets = [
#    { binding = "SSR_BUCKET", bucket_name = "ssr_cache_p1" }
#]

[env.ohg-p1.vars]
ORIGIN_HOST = "www.ohgar.com"
ORIGIN_PROTOCOL = "https"
ORIGIN_PORT = "443"
FORCED_EDGE_CACHE_CONTROL = "public, max-age=28800"
TRACKING_PARAMS = "gclid,gclsrc,fbclid,utm_source,utm_medium,utm_campaign,utm_content"
SSR_RETRIES = "2000,2000,2000,2000"

[env.fs-s1]
name = "p1-www-ssr-cache-v2"
routes = ["https://cdn.forumsport.com/es-es/nutricion-y-salud/productos/complementos-nutricionales-NU033-c*"]
analytics_engine_datasets = [
    { binding = "SSR_CACHE", dataset = "ssr_cache_p1" }
]

[[env.fs-s1.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ssr"         # Set this to your R2 bucket name. Required
preview_bucket_name = "ssr" # Set this to your preview R2 bucket name. Can be equal to bucket_name. Optional

[env.fs-s1.vars]
ORIGIN_HOST = "www.forumsport.com"
ORIGIN_PROTOCOL = "https"
ORIGIN_PORT = "443"
FORCED_EDGE_CACHE_CONTROL = "public, max-age=28800"
TRACKING_PARAMS = "gclid,gclsrc,fbclid,utm_source,utm_medium,utm_campaign,utm_content"
SSR_RETRIES = "2000,2000,2000,2000"
R2_PREFIX = "001"

[env.wow-s1]
name = "s1-www-ssr-cache-v2"
routes = ["s1-www.wowconcept.com/es", "s1-www.wowconcept.com/es/*"]
analytics_engine_datasets = [
    { binding = "SSR_CACHE", dataset = "ssr_cache_s1_v1" }
]

[[env.wow-s1.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ssr"         # Set this to your R2 bucket name. Required
preview_bucket_name = "ssr" # Set this to your preview R2 bucket name. Can be equal to bucket_name. Optional

[env.wow-s1.vars]
ORIGIN_HOST = "s1-www.wowconcept.com"
ORIGIN_PROTOCOL = "https"
ORIGIN_PORT = "443"
FORCED_EDGE_CACHE_CONTROL = "public, max-age=28800"
TRACKING_PARAMS = "gclid,gclsrc,fbclid,utm_source,utm_medium,utm_campaign,utm_content"
SSR_RETRIES = "7000,10000,10000,20000"
R2_PREFIX = "001"

[env.wow-p1]
name = "p1-www-ssr-cache-v2"
routes = ["wowconcept.com/es/product/LAC2SNE33734PCM001/test-ssr*"]
analytics_engine_datasets = [
    { binding = "SSR_CACHE", dataset = "ssr_cache_p1_v1" }
]

[[env.wow-p1.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ssr"         # Set this to your R2 bucket name. Required
preview_bucket_name = "ssr" # Set this to your preview R2 bucket name. Can be equal to bucket_name. Optional

[env.wow-p1.vars]
ORIGIN_HOST = "wowconcept.com"
ORIGIN_PROTOCOL = "https"
ORIGIN_PORT = "443"
FORCED_EDGE_CACHE_CONTROL = "public, max-age=28800"
TRACKING_PARAMS = "gclid,gclsrc,fbclid,utm_source,utm_medium,utm_campaign,utm_content"
SSR_RETRIES = "7000,10000,10000,20000"
R2_PREFIX = "001"