{
 "title": "WoW SSR",
 "tags": [
  "ssr",
  "wow",
  "cloudflare",
  "cache"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "renderingmode",
    "label": "rendering mode",
    "query": "SELECT rendering_mode FROM (\nSELECT\n     blob3 AS rendering_mode,\n     count() as rank\nFROM ssr_cache_p1_v1\nWHERE LENGTH(rendering_mode) > 0\nGROUP BY rendering_mode\norder by rendering_mode asc\n)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "SELECT cf_cache_status FROM (\nSELECT\n     blob4 AS cf_cache_status,\n     count() as rank\nFROM ssr_cache_p1_v1\nWHERE LENGTH(cf_cache_status) > 0\nGROUP BY cf_cache_status\norder by cf_cache_status asc\n)"
   },
   {
    "name": "source",
    "label": "source",
    "query": "SELECT cf_cache_source FROM (\nSELECT\n     blob5 AS cf_cache_source,\n     count() as rank\nFROM ssr_cache_p1_v1\nWHERE LENGTH(cf_cache_source) > 0\nGROUP BY cf_cache_source\norder by cf_cache_source asc\n)"
   },
   {
    "name": "country",
    "label": "country",
    "query": "SELECT country FROM (\nSELECT\n     blob8 AS country,\n     count()\nFROM ssr_cache_p1_v1\nWHERE LENGTH(country) > 0\nGROUP BY country\norder by country asc\n)"
   },
   {
    "name": "useragent",
    "label": "user-agent",
    "query": "SELECT useragent FROM (\nSELECT\n     blob10 AS useragent,\n     count()\nFROM ssr_cache_p1_v1\nWHERE length(blob10) > 0\nGROUP BY useragent\norder by useragent asc\n)"
   },
   {
    "name": "colo",
    "label": "colo",
    "query": "SELECT colo FROM (\nSELECT\n     blob9 AS colo,\n     count() as rank\nFROM ssr_cache_p1_v1\nWHERE length(colo) > 0\nGROUP BY colo\norder by colo asc\n)"
   },
   {
    "name": "attempt",
    "label": "attempt",
    "query": "SELECT attempt FROM (\nSELECT\n     double1 AS attempt,\n     count()\nFROM ssr_cache_p1_v1\nGROUP BY attempt\norder by attempt asc\n)"
   },
   {
    "name": "httpstatus",
    "label": "http status",
    "query": "SELECT http_status FROM (\nSELECT\n     double3 AS http_status,\n     count()\nFROM ssr_cache_p1_v1\nGROUP BY http_status\norder by http_status asc\n)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HIT ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    blob4 AS cf_cache_status,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY cf_cache_status\n",
     "rawQuery": "SELECT\n    blob4 AS cf_cache_status,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039483) AND timestamp <= toDateTime(1689082683)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY cf_cache_status",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    blob5 AS cf_cache_source,\n    count() AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\n    \nGROUP BY cf_cache_source\n\nORDER BY cf_cache_source ASC\n",
     "rawQuery": "SELECT\n    blob5 AS cf_cache_source,\n    count() AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039489) AND timestamp <= toDateTime(1689082689)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\n    \nGROUP BY cf_cache_source\n\nORDER BY cf_cache_source ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Colos",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    blob9 AS colo,\n    count() AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY colo\n\nORDER BY value DESC\n",
     "rawQuery": "SELECT\n    blob9 AS colo,\n    count() AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039497) AND timestamp <= toDateTime(1689082697)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY colo\n\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Attempts",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    format('{}', double1) AS attempt,\n    count() AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY attempt\n\nORDER BY value DESC\n",
     "rawQuery": "SELECT\n    format('{}', double1) AS attempt,\n    count() AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039506) AND timestamp <= toDateTime(1689082706)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY attempt\n\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  { "title": "HIT ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HIT ratio",
   "type": "timeseries",
   "description": "Correlates average response time and count of requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    if(blob4 = 'HIT', '01-HIT', if(blob4 = 'EXPIRED', '02-EXPIRED', if(blob4 = 'MISS', '03-MISS', if(blob4 = 'BYPASS', '04-BYPASS', if(blob4 = 'DYNAMIC', '05-DYNAMIC', '00-N/A'))))) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and($status = 'all' OR blob4 in ($status))\n    and($source = 'all' OR blob5 in ($source))\n    and($useragent = 'all' OR blob10 IN ($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY\n    t,\n    metric\nORDER BY\n    metric desc",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 AS t,\n    if(blob4 = 'HIT', '01-HIT', if(blob4 = 'EXPIRED', '02-EXPIRED', if(blob4 = 'MISS', '03-MISS', if(blob4 = 'BYPASS', '04-BYPASS', if(blob4 = 'DYNAMIC', '05-DYNAMIC', '00-N/A'))))) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039555) AND timestamp <= toDateTime(1689082755)\n    and index1 = 'L0'\n    and('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and('all' = 'all' OR blob4 in ('all'))\n    and('all' = 'all' OR blob5 in ('all'))\n    and('all' = 'all' OR blob10 IN ('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY\n    t,\n    metric\nORDER BY\n    metric desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Response time vS. Cache status time series",
   "type": "timeseries",
   "description": "Correlates average response time and count of requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    format('duration_{}', blob4) AS metric,\n    SUM(_sample_interval * double2) / SUM(_sample_interval) AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY\n    t,\n    metric\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 AS t,\n    format('duration_{}', blob4) AS metric,\n    SUM(_sample_interval * double2) / SUM(_sample_interval) AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039579) AND timestamp <= toDateTime(1689082779)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY\n    t,\n    metric\nORDER BY t",
     "round": "0s"
    },
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    format('count_{}', blob4) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY\n    t,\n    metric\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 AS t,\n    format('count_{}', blob4) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039579) AND timestamp <= toDateTime(1689082779)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY\n    t,\n    metric\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  { "title": "Handler ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Handler ratio",
   "type": "timeseries",
   "description": "Correlates average response time and count of requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    format('count_{}', blob5) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY\n    t,\n    metric\nORDER BY metric desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 AS t,\n    format('count_{}', blob5) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039515) AND timestamp <= toDateTime(1689082715)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY\n    t,\n    metric\nORDER BY metric desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Response time vS. Cache source time series",
   "type": "timeseries",
   "description": "Correlates average response time and count of requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    format('duration_{}', blob5) AS metric,\n    SUM(_sample_interval * double2) / SUM(_sample_interval) AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY\n    t,\n    metric\nORDER BY t asc, metric desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 AS t,\n    format('duration_{}', blob5) AS metric,\n    SUM(_sample_interval * double2) / SUM(_sample_interval) AS value\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039531) AND timestamp <= toDateTime(1689082731)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY\n    t,\n    metric\nORDER BY t asc, metric desc",
     "round": "0s"
    },
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    format('count_{}', blob5) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    $timeFilter\n    and index1 = 'L0'\n    and ($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and ($country = 'all' OR blob8 in ($country))\n    and ($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and ($status = 'all' OR blob4 in ($status))\n    and ($source = 'all' OR blob5 in ($source))\n    and ($useragent = 'all' OR blob10 IN($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nGROUP BY\n    t,\n    metric\nORDER BY t asc, metric desc\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 AS t,\n    format('count_{}', blob5) AS metric,\n    count()\nFROM ssr_cache_p1_v1\n\nWHERE\n    timestamp >= toDateTime(1689039531) AND timestamp <= toDateTime(1689082731)\n    and index1 = 'L0'\n    and ('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and ('ES' = 'all' OR blob8 in ('ES'))\n    and ('all' = 'all' OR blob3 in ('all'))\n    and ('all' = 'all' OR blob4 in ('all'))\n    and ('all' = 'all' OR blob5 in ('all'))\n    and ('all' = 'all' OR blob10 IN('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (200)\nGROUP BY\n    t,\n    metric\nORDER BY t asc, metric desc",
     "round": "0s"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    timestamp,\n    index1 AS handler,\n    blob1 AS cf_ray,\n    blob2 AS url,\n    blob3 AS rendering_mode,\n    blob4 AS cf_cache_status,\n    blob5 as cf_cache_source,\n    blob6 as city,\n    blob7 as region,\n    blob8 as country,\n    blob9 as colo,\n    blob10 as user_agent,\n    double3 as http_status,\n    double1 as attempt,\n    double2 as duration\nFROM ssr_cache_p1_v1\nWHERE\n    $timeFilter \n    and index1 = 'L0'\n    and($colo = 'all' OR blob9 IN ($colo))\n    and toUInt32(double1) IN ($attempt)\n    and($country = 'all' OR blob8 in ($country))\n    and($renderingmode = 'all' OR blob3 in ($renderingmode))\n    and($status = 'all' OR blob4 in ($status))\n    and($source = 'all' OR blob5 in ($source))\n    and($useragent = 'all' OR blob10 IN ($useragent) OR length(blob10) = 0)\n    and toUInt32(double3) IN ($httpstatus)\nORDER BY\n    timestamp DESC,\n    cf_ray ASC,\n    handler ASC",
     "rawQuery": "SELECT\n    timestamp,\n    index1 AS handler,\n    blob1 AS cf_ray,\n    blob2 AS url,\n    blob3 AS rendering_mode,\n    blob4 AS cf_cache_status,\n    blob5 as cf_cache_source,\n    blob6 as city,\n    blob7 as region,\n    blob8 as country,\n    blob9 as colo,\n    blob10 as user_agent,\n    double3 as http_status,\n    double1 as attempt,\n    double2 as duration\nFROM ssr_cache_p1_v1\nWHERE\n    timestamp >= toDateTime(1689039624) AND timestamp <= toDateTime(1689082824) \n    and index1 = 'L0'\n    and('all' = 'all' OR blob9 IN ('all'))\n    and toUInt32(double1) IN (0,1,2,3,4)\n    and('ES' = 'all' OR blob8 in ('ES'))\n    and('all' = 'all' OR blob3 in ('all'))\n    and('all' = 'all' OR blob4 in ('all'))\n    and('all' = 'all' OR blob5 in ('all'))\n    and('all' = 'all' OR blob10 IN ('all') OR length(blob10) = 0)\n    and toUInt32(double3) IN (0,200,206,304)\nORDER BY\n    timestamp DESC,\n    cf_ray ASC,\n    handler ASC",
     "round": "0s"
    }
   ]
  }
 ]
}